version: '3'

services:
  php-web60002:
    image: niclab/php8.0
    container_name: php-web60002
    working_dir: /var/www
    ports:
      - 60002:80
    volumes:
      - "./root:/var/www"
      - "./docker/php-web/php.ini:/usr/local/etc/php/php.ini"
      - "./docker/php-web/custom-vhost.conf:/etc/apache2/sites-available/000-default.conf"

  mysql60102:
    image: library/mysql:5.7
    container_name: mysql60102
    ports:
      - 60102:3306
    volumes:
      - ./docker/mysql/initdb.d:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=tide
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql60102
      - PMA_USER=user
      - PMA_PASSWORD=password
    links:
      - mysql60102
    ports:
      - 60202:80
    volumes:
      - ./docker/phpmyadmin/phpmyadmin-misc.ini:/usr/local/etc/php/conf.d/phpmyadmin-misc.ini
